# Generated by Django 3.2 on 2021-04-28 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserExtraInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('userType', models.CharField(max_length=120)),
                ('regist_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
